sftp:
    image: pollenm/docker_sftp
    restart: always
    volumes:
        - ./config/keys/id_rsa_platypus.pub:/home/platypus/.ssh/keys/id_rsa.pub:ro
        - ./data/home:/home/
    ports:
        - "2222:22"
    command: platypus::1001::/data
